const $ = (id) => document.getElementById(id);
const esc = (value) => { const node = document.createElement('span'); node.textContent = value ?? ''; return node.innerHTML; };
async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || '请求失败'); return data; }
function initializeTheme() { const key = 'ry-aletheia-theme'; const apply = () => { const light = localStorage.getItem(key) === 'light'; document.body.classList.toggle('theme-light', light); document.documentElement.style.colorScheme = light ? 'light' : 'dark'; }; const toggle = () => { localStorage.setItem(key, document.body.classList.contains('theme-light') ? 'dark' : 'light'); apply(); }; const mark = document.querySelector('.brand .mark'); mark?.addEventListener('click', toggle); mark?.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); toggle(); } }); if (mark) { mark.tabIndex = 0; mark.setAttribute('role', 'button'); } apply(); }
initializeTheme();
const lifecycleOptions = (value) => [['draft', '草拟'], ['local_verified', '本机已验证'], ['published', '可交付'], ['deprecated', '已停用']].map(([id, label]) => `<option value="${id}" ${id === value ? 'selected' : ''}>${label}</option>`).join('');
const scenarioOptions = (profiles, selectedId) => `<option value="">未绑定（常规配置）</option>${profiles.map((profile) => `<option value="${esc(profile.id)}" ${profile.id === selectedId ? 'selected' : ''}>${esc(profile.name)}</option>`).join('')}`;
function message(text, error = false) { $('caseMessage').textContent = text; $('caseMessage').style.color = error ? '#ff899a' : '#35d69c'; }

async function saveAlias(id, input) { const settings = await request('/api/settings'); const aliases = settings.case_aliases || {}; const value = input.value.trim(); if (value) aliases[id] = value; else delete aliases[id]; await request('/api/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ case_aliases: aliases }) }); message('用例别名已保存。'); await loadCases(); }
async function bindScenario(caseId, select) { const data = await request('/api/scenario-setup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'bind-case', case_id: caseId, profile_id: select.value }) }); message(data.message); }
async function saveManagement(id, row) { const payload = { version: row.querySelector('[data-version]').value.trim(), lifecycle: row.querySelector('[data-lifecycle]').value, tags: row.querySelector('[data-tags]').value.split(',').map((item) => item.trim()).filter(Boolean), summary: row.querySelector('[data-summary]').value.trim() }; await request(`/api/cases/${encodeURIComponent(id)}/management`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); message('用例管理信息已保存。'); await loadCases(); }
function managementControls(item) { const data = item.management || {}; const tags = Array.isArray(data.tags) ? data.tags.join(', ') : ''; return `<details class="case-management"><summary>用例管理与交付</summary><div class="management-grid"><label>版本<input data-version value="${esc(data.version || '0.1.0')}" maxlength="32"></label><label>状态<select data-lifecycle>${lifecycleOptions(data.lifecycle || 'draft')}</select></label><label>标签<input data-tags value="${esc(tags)}" placeholder="电梯, 回环, 夜间"></label><label class="management-summary">说明<input data-summary value="${esc(data.summary || '')}" maxlength="300" placeholder="适用场景、前提或限制"></label></div><div class="management-actions"><button class="compact-action save-management" data-id="${esc(item.id)}" type="button">保存管理信息</button><button class="compact-action export-case" data-id="${esc(item.id)}" type="button">⇩ 导出用例包</button><small>导出不包含本车启动方案、依赖节点或绝对路径。</small></div></details>`; }
async function loadCases() { try { const [data, scenario] = await Promise.all([request('/api/cases'), request('/api/scenario-setup')]); const profiles = scenario.document?.profiles || []; const bindings = scenario.document?.case_bindings || {}; $('caseTotal').textContent = data.cases.length; $('issueCount').textContent = data.validationIssues.length ? `${data.validationIssues.length} 项提示` : '校验通过'; $('issueCount').className = `badge ${data.validationIssues.length ? 'muted' : ''}`; $('caseList').innerHTML = data.cases.length ? data.cases.map((item) => `<div class="asset-row case-row"><div><b>${esc(item.alias || item.filename)}</b><small>${esc(item.filename)} · ${esc(item.name)}</small></div><div><span class="file-kind">${esc(item.management?.lifecycle || 'draft').replace('_', ' ').toUpperCase()}</span><small>版本 ${esc(item.management?.version || '0.1.0')} · SHA-256 ${esc((item.management?.fingerprint?.sha256 || '未计算').slice(0, 12))}</small></div><div class="case-controls"><input data-alias="${esc(item.id)}" value="${esc(item.alias || '')}" placeholder="场景别名"><button class="compact-action save-alias" data-id="${esc(item.id)}" type="button">保存别名</button><select data-scenario="${esc(item.id)}">${scenarioOptions(profiles, bindings[item.id])}</select><button class="compact-action save-scenario" data-id="${esc(item.id)}" type="button">保存方案</button></div>${managementControls(item)}</div>`).join('') : '<div class="page-empty">tasks/ 中尚未发现有效任务文件。</div>'; $('issueList').innerHTML = data.validationIssues.length ? data.validationIssues.map((item) => `<div class="asset-row"><div><b>${esc(item.filename)}</b></div><div class="page-muted">${esc(item.message)}</div><div><span class="file-kind">NEEDS REVIEW</span></div></div>`).join('') : '<div class="page-empty">所有已发现 JSON 均通过基础校验。</div>'; } catch (error) { $('caseList').innerHTML = `<div class="page-empty">读取失败：${esc(error.message)}</div>`; } }
async function downloadPackage(id) { const response = await fetch(`/api/cases/${encodeURIComponent(id)}/export`); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || '导出失败'); } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'ry-aletheia-case.rycase.zip'; document.body.append(link); link.click(); link.remove(); URL.revokeObjectURL(url); message('用例包已导出。'); }
document.addEventListener('click', (event) => { const alias = event.target.closest('.save-alias'); if (alias) { saveAlias(alias.dataset.id, document.querySelector(`[data-alias="${CSS.escape(alias.dataset.id)}"]`)).catch((error) => message(error.message, true)); return; } const scenario = event.target.closest('.save-scenario'); if (scenario) { bindScenario(scenario.dataset.id, document.querySelector(`[data-scenario="${CSS.escape(scenario.dataset.id)}"]`)).catch((error) => message(error.message, true)); return; } const management = event.target.closest('.save-management'); if (management) { saveManagement(management.dataset.id, management.closest('.asset-row')).catch((error) => message(error.message, true)); return; } const exported = event.target.closest('.export-case'); if (exported) downloadPackage(exported.dataset.id).catch((error) => message(error.message, true)); });
$('refreshCases').addEventListener('click', loadCases); loadCases();
function setUploadMessage(targetId, text, error = false) { const target = $(targetId); target.textContent = text; target.style.color = error ? '#ff899a' : '#35d69c'; }
function uploadFile(file, kind) { if (!file) return; const isPackage = kind === 'package'; const messageId = isPackage ? 'packageUploadMessage' : 'caseUploadMessage'; const hintId = isPackage ? 'packageUploadHint' : 'caseUploadHint'; if ((isPackage && !file.name.toLowerCase().endsWith('.rycase.zip')) || (!isPackage && !file.name.toLowerCase().endsWith('.json'))) { setUploadMessage(messageId, isPackage ? '仅支持 .rycase.zip 用例包。' : '仅支持 .json 任务文件。', true); return; } if (file.size < 1 || file.size > 8 * 1024 * 1024) { setUploadMessage(messageId, '文件大小必须在 1 B 到 8 MiB 之间。', true); return; } const upload = new XMLHttpRequest(); $(hintId).textContent = `${file.name} · ${(file.size / 1024).toFixed(1)} KiB`; setUploadMessage(messageId, isPackage ? '正在校验并导入用例包…' : '正在导入并校验用例文件…'); upload.open('POST', isPackage ? '/api/case-packages/import' : '/api/cases/upload'); upload.setRequestHeader('Content-Type', isPackage ? 'application/zip' : 'application/json; charset=utf-8'); if (!isPackage) upload.setRequestHeader('X-Case-Filename', encodeURIComponent(file.name)); upload.onerror = () => setUploadMessage(messageId, '上传连接中断，未确认写入任务目录。', true); upload.onload = async () => { let data = {}; try { data = JSON.parse(upload.responseText); } catch (_) {} if (upload.status >= 200 && upload.status < 300) { setUploadMessage(messageId, data.message || `已导入：${data.case?.filename || file.name}`); $(isPackage ? 'packageUploadFile' : 'caseUploadFile').value = ''; await loadCases(); } else setUploadMessage(messageId, data.error || `导入失败（HTTP ${upload.status}）`, true); }; upload.send(file); }
$('caseUploadFile').addEventListener('change', (event) => uploadFile(event.target.files[0], 'json')); $('packageUploadFile').addEventListener('change', (event) => uploadFile(event.target.files[0], 'package')); [['caseDropzone', 'json'], ['packageDropzone', 'package']].forEach(([id, kind]) => { const target = $(id); target.addEventListener('dragover', (event) => { event.preventDefault(); target.classList.add('dragover'); }); target.addEventListener('dragleave', () => target.classList.remove('dragover')); target.addEventListener('drop', (event) => { event.preventDefault(); target.classList.remove('dragover'); uploadFile(event.dataTransfer.files[0], kind); }); });
