/// The single source of truth for debug UI review coverage.
///
/// This file deliberately has no Flutter imports. It is shared by the in-app
/// debug gallery, the Markdown inventory generator and the golden test suite.
library;

enum GalleryModule {
  robot('首页'),
  observe('观测'),
  tools('工具'),
  settings('设置'),
  global('全局组件');

  const GalleryModule(this.label);

  final String label;
}

enum GallerySurface {
  robot,
  observationMap,
  observationVideo,
  toolsHome,
  testRuns,
  testCases,
  logs,
  reports,
  runtimeSettings,
  scenarioSetup,
  maintenance,
  appSettings,
  appUpdate,
  appFeedback,
  dialog,
  bottomSheet,
  snackbar,
  permission,
  offline,
  empty,
}

enum GalleryAppearance { hmiDark, daylight }

class GalleryScreenSpec {
  const GalleryScreenSpec({
    required this.id,
    required this.module,
    required this.title,
    required this.route,
    required this.state,
    required this.trigger,
    required this.surface,
    required this.screenshotPath,
    this.hasScreenshot = true,
    this.focusTestRunDetails = false,
    this.focusFeedbackAttachments = false,
    this.showUpdateCheckResult = false,
    this.appearance = GalleryAppearance.hmiDark,
  });

  /// Stable identifier used by deep links, tests and screenshot file names.
  final String id;
  final GalleryModule module;
  final String title;
  final String route;
  final String state;
  final String trigger;
  final GallerySurface surface;

  /// Relative to `docs/ui/screens/`.
  final String screenshotPath;
  final bool hasScreenshot;

  /// Debug-only review affordance: preserves the actual page but opens a
  /// long test page at its production run-detail section.
  final bool focusTestRunDetails;

  /// Shows the lower attachment and diagnostics portion of the real feedback
  /// form in a deterministic gallery screenshot.
  final bool focusFeedbackAttachments;

  /// Displays the result of the development-only App update check.
  final bool showUpdateCheckResult;

  /// The handset appearance required to reproduce this visual state.
  final GalleryAppearance appearance;
}

const galleryScreenManifest = <GalleryScreenSpec>[
  GalleryScreenSpec(
    id: 'app_settings_ready',
    module: GalleryModule.settings,
    title: '应用设置',
    route: '/settings',
    state: '本机偏好与版本信息',
    trigger: '从一级设置入口打开',
    surface: GallerySurface.appSettings,
    screenshotPath: 'settings/app-settings-ready.png',
  ),
  GalleryScreenSpec(
    id: 'app_update_ready',
    module: GalleryModule.settings,
    title: '检查更新',
    route: '/settings/update',
    state: '当前开发版本未接入在线服务',
    trigger: '从设置的检查更新入口打开',
    surface: GallerySurface.appUpdate,
    screenshotPath: 'settings/update-ready.png',
    showUpdateCheckResult: true,
  ),
  GalleryScreenSpec(
    id: 'app_feedback_draft',
    module: GalleryModule.settings,
    title: '问题与建议',
    route: '/settings/feedback',
    state: '已填写并附加截图',
    trigger: '从设置打开问题反馈',
    surface: GallerySurface.appFeedback,
    screenshotPath: 'settings/feedback-draft.png',
  ),
  GalleryScreenSpec(
    id: 'app_feedback_attachments',
    module: GalleryModule.settings,
    title: '问题与建议',
    route: '/settings/feedback',
    state: '截图与诊断摘要已选择',
    trigger: '填写反馈后继续查看附加信息',
    surface: GallerySurface.appFeedback,
    screenshotPath: 'settings/feedback-attachments.png',
    focusFeedbackAttachments: true,
  ),
  GalleryScreenSpec(
    id: 'robot_disconnected',
    module: GalleryModule.robot,
    title: '首页',
    route: '/robot',
    state: '未连接',
    trigger: '首次打开或主动断开连接',
    surface: GallerySurface.robot,
    screenshotPath: 'robot/disconnected.png',
  ),
  GalleryScreenSpec(
    id: 'robot_restoring',
    module: GalleryModule.robot,
    title: '首页',
    route: '/robot',
    state: '正在恢复连接',
    trigger: '保存的机器人地址正在验证',
    surface: GallerySurface.robot,
    screenshotPath: 'robot/restoring.png',
  ),
  GalleryScreenSpec(
    id: 'robot_connecting',
    module: GalleryModule.robot,
    title: '首页',
    route: '/robot',
    state: '正在连接',
    trigger: '用户提交机器人地址后',
    surface: GallerySurface.robot,
    screenshotPath: 'robot/connecting.png',
  ),
  GalleryScreenSpec(
    id: 'robot_connected',
    module: GalleryModule.robot,
    title: '首页',
    route: '/robot',
    state: '已连接，健康正常',
    trigger: '连接和健康检查均成功',
    surface: GallerySurface.robot,
    screenshotPath: 'robot/connected.png',
  ),
  GalleryScreenSpec(
    id: 'robot_connection_failed',
    module: GalleryModule.robot,
    title: '首页',
    route: '/robot',
    state: '连接失败',
    trigger: '地址不可达或服务未响应',
    surface: GallerySurface.robot,
    screenshotPath: 'robot/connection-failed.png',
  ),
  GalleryScreenSpec(
    id: 'robot_network_error',
    module: GalleryModule.robot,
    title: '首页',
    route: '/robot',
    state: '网络异常',
    trigger: '已连接后的网络请求失败',
    surface: GallerySurface.robot,
    screenshotPath: 'robot/network-error.png',
  ),
  GalleryScreenSpec(
    id: 'robot_health_warning',
    module: GalleryModule.robot,
    title: '首页',
    route: '/robot',
    state: '健康状态异常',
    trigger: '健康检查返回异常状态',
    surface: GallerySurface.robot,
    screenshotPath: 'robot/health-warning.png',
  ),
  GalleryScreenSpec(
    id: 'observe_disconnected',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '需要连接机器人',
    trigger: '未连接时打开观测',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/disconnected.png',
  ),
  GalleryScreenSpec(
    id: 'observe_loading',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '正在准备地图',
    trigger: '进入观测且地图尚未返回',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/loading.png',
  ),
  GalleryScreenSpec(
    id: 'observe_empty',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '等待活动地图',
    trigger: '服务可用但未提供地图',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/empty-map.png',
  ),
  GalleryScreenSpec(
    id: 'observe_unavailable',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '观测暂不可用',
    trigger: '观测服务暂不可用',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/unavailable.png',
  ),
  GalleryScreenSpec(
    id: 'observe_error',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '读取失败',
    trigger: '地图请求失败',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/error.png',
  ),
  GalleryScreenSpec(
    id: 'observe_live',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '地图、位置、点云正常',
    trigger: '地图与遥测已收到',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/live-map.png',
  ),
  GalleryScreenSpec(
    id: 'observe_live_daylight',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '日间模式',
    trigger: '在设置中切换日间模式后进入观测',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/live-daylight.png',
    appearance: GalleryAppearance.daylight,
  ),
  GalleryScreenSpec(
    id: 'observe_telemetry_interrupted',
    module: GalleryModule.observe,
    title: '实时观测',
    route: '/observation',
    state: '位置或点云断流',
    trigger: '独立遥测流断开或超过新鲜度阈值',
    surface: GallerySurface.observationMap,
    screenshotPath: 'observe/telemetry-interrupted.png',
  ),
  GalleryScreenSpec(
    id: 'video_loading',
    module: GalleryModule.observe,
    title: '相机',
    route: '/observation',
    state: '正在读取视频状态',
    trigger: '进入相机工作区',
    surface: GallerySurface.observationVideo,
    screenshotPath: 'observe/video-loading.png',
  ),
  GalleryScreenSpec(
    id: 'video_empty',
    module: GalleryModule.observe,
    title: '相机',
    route: '/observation',
    state: '没有可用视频流',
    trigger: '视频状态成功但没有流',
    surface: GallerySurface.observationVideo,
    screenshotPath: 'observe/video-empty.png',
  ),
  GalleryScreenSpec(
    id: 'video_waiting',
    module: GalleryModule.observe,
    title: '相机',
    route: '/observation',
    state: '视频流等待可用',
    trigger: '视频流存在但尚未上线',
    surface: GallerySurface.observationVideo,
    screenshotPath: 'observe/video-waiting.png',
  ),
  GalleryScreenSpec(
    id: 'video_offline',
    module: GalleryModule.observe,
    title: '相机',
    route: '/observation',
    state: '视频流离线',
    trigger: '视频流返回 offline',
    surface: GallerySurface.observationVideo,
    screenshotPath: 'observe/video-offline.png',
  ),
  GalleryScreenSpec(
    id: 'video_ready',
    module: GalleryModule.observe,
    title: '相机',
    route: '/observation',
    state: '六路视频可选，主画面正常',
    trigger: '视频服务返回多个 online 流',
    surface: GallerySurface.observationVideo,
    screenshotPath: 'observe/video-ready.png',
  ),
  GalleryScreenSpec(
    id: 'video_error',
    module: GalleryModule.observe,
    title: '相机',
    route: '/observation',
    state: '视频状态读取失败',
    trigger: '视频状态接口请求失败',
    surface: GallerySurface.observationVideo,
    screenshotPath: 'observe/video-error.png',
  ),
  GalleryScreenSpec(
    id: 'tools_disconnected',
    module: GalleryModule.tools,
    title: '工具',
    route: '/tools',
    state: '未连接',
    trigger: '未选择可用机器人',
    surface: GallerySurface.toolsHome,
    screenshotPath: 'tools/disconnected.png',
  ),
  GalleryScreenSpec(
    id: 'tools_connected',
    module: GalleryModule.tools,
    title: '工具',
    route: '/tools',
    state: '可用工具入口',
    trigger: '机器人已连接',
    surface: GallerySurface.toolsHome,
    screenshotPath: 'tools/connected.png',
  ),
  GalleryScreenSpec(
    id: 'runtime_settings_ready',
    module: GalleryModule.tools,
    title: '运行配置',
    route: '/tools/runtime',
    state: '受控参数与依赖编排',
    trigger: '连接机器人后打开运行配置',
    surface: GallerySurface.runtimeSettings,
    screenshotPath: 'tools/runtime-settings-ready.png',
  ),
  GalleryScreenSpec(
    id: 'scenario_setup_ready',
    module: GalleryModule.tools,
    title: '场景前置配置',
    route: '/tools/scenario-setup',
    state: '方案可预览，当前常规配置',
    trigger: '连接机器人后打开场景前置配置',
    surface: GallerySurface.scenarioSetup,
    screenshotPath: 'tools/scenario-setup-ready.png',
  ),
  GalleryScreenSpec(
    id: 'scenario_setup_pending_restore',
    module: GalleryModule.tools,
    title: '场景前置配置',
    route: '/tools/scenario-setup',
    state: '已有方案待恢复',
    trigger: '手动应用场景方案后',
    surface: GallerySurface.scenarioSetup,
    screenshotPath: 'tools/scenario-setup-pending-restore.png',
  ),
  GalleryScreenSpec(
    id: 'scenario_setup_file_preview',
    module: GalleryModule.tools,
    title: '场景前置配置',
    route: '/tools/scenario-setup',
    state: '受控文件预览',
    trigger: '在受控目录浏览器中选择文件',
    surface: GallerySurface.scenarioSetup,
    screenshotPath: 'tools/scenario-setup-file-preview.png',
  ),
  GalleryScreenSpec(
    id: 'maintenance_ready',
    module: GalleryModule.tools,
    title: '控制台服务',
    route: '/tools/maintenance',
    state: '服务运行中',
    trigger: '连接机器人后打开控制台服务',
    surface: GallerySurface.maintenance,
    screenshotPath: 'tools/maintenance-ready.png',
  ),
  GalleryScreenSpec(
    id: 'test_disconnected',
    module: GalleryModule.tools,
    title: '测试',
    route: '/tools/testing',
    state: '需要连接机器人',
    trigger: '从工具进入测试但未连接',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-disconnected.png',
  ),
  GalleryScreenSpec(
    id: 'test_cases_loading',
    module: GalleryModule.tools,
    title: '测试',
    route: '/tools/testing',
    state: '正在加载测试内容',
    trigger: '已连接且用例目录未返回',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-cases-loading.png',
  ),
  GalleryScreenSpec(
    id: 'test_cases_error',
    module: GalleryModule.tools,
    title: '测试',
    route: '/tools/testing',
    state: '无法读取测试内容',
    trigger: '用例目录请求失败',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-cases-error.png',
  ),
  GalleryScreenSpec(
    id: 'test_empty',
    module: GalleryModule.tools,
    title: '测试',
    route: '/tools/testing',
    state: '暂无测试任务',
    trigger: '测试内容存在但尚无运行记录',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-empty.png',
  ),
  GalleryScreenSpec(
    id: 'test_queued',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '排队中',
    trigger: '任务状态为 queued',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-queued.png',
  ),
  GalleryScreenSpec(
    id: 'test_preparing',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '准备中',
    trigger: '任务状态为 preparing',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-preparing.png',
  ),
  GalleryScreenSpec(
    id: 'test_running',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '执行中',
    trigger: '任务状态为 running',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-running.png',
  ),
  GalleryScreenSpec(
    id: 'test_stall_alert',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '运行停滞，等待人工处置',
    trigger: '轨迹监测返回 alert=true',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-stall-alert.png',
    focusTestRunDetails: true,
  ),
  GalleryScreenSpec(
    id: 'test_trajectory_evidence',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '轮次已生成地图轨迹证据',
    trigger: '测试轮次完成且服务端已写入 SVG 证据',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-trajectory-evidence.png',
    focusTestRunDetails: true,
  ),
  GalleryScreenSpec(
    id: 'test_supervisor_waiting',
    module: GalleryModule.tools,
    title: '运行依赖',
    route: '/tools/testing',
    state: '等待 Supervisor 预检',
    trigger: '测试已创建，尚未返回本机 Supervisor 快照',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/supervisor-waiting.png',
    focusTestRunDetails: true,
  ),
  GalleryScreenSpec(
    id: 'test_supervisor_ready',
    module: GalleryModule.tools,
    title: '运行依赖',
    route: '/tools/testing',
    state: 'Supervisor 节点全部运行',
    trigger: '全部必需节点返回 RUNNING',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/supervisor-ready.png',
    focusTestRunDetails: true,
  ),
  GalleryScreenSpec(
    id: 'test_supervisor_optional_warning',
    module: GalleryModule.tools,
    title: '运行依赖',
    route: '/tools/testing',
    state: '可选节点正在重试',
    trigger: '可选 Supervisor 节点返回 BACKOFF，必需节点仍正常',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/supervisor-optional-warning.png',
    focusTestRunDetails: true,
  ),
  GalleryScreenSpec(
    id: 'test_supervisor_required_failure',
    module: GalleryModule.tools,
    title: '运行依赖',
    route: '/tools/testing',
    state: '必需节点异常',
    trigger: '必需 Supervisor 节点返回 FATAL、STOPPED 或 MISSING',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/supervisor-required-failure.png',
    focusTestRunDetails: true,
  ),
  GalleryScreenSpec(
    id: 'test_supervisor_recovery',
    module: GalleryModule.tools,
    title: '运行依赖',
    route: '/tools/testing',
    state: '人工恢复后的依赖复检',
    trigger: '运行进入 awaiting_recovery，依赖正在恢复或重试',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/supervisor-recovery.png',
    focusTestRunDetails: true,
  ),
  GalleryScreenSpec(
    id: 'test_awaiting_recovery',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '等待恢复',
    trigger: '任务状态为 awaitingRecovery',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-awaiting-recovery.png',
  ),
  GalleryScreenSpec(
    id: 'test_recovering',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '恢复中',
    trigger: '任务状态为 recovering',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-recovering.png',
  ),
  GalleryScreenSpec(
    id: 'test_cancelling',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '正在中止',
    trigger: '任务状态为 cancelling',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-cancelling.png',
  ),
  GalleryScreenSpec(
    id: 'test_cancelled',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '已中止',
    trigger: '任务状态为 cancelled',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-cancelled.png',
  ),
  GalleryScreenSpec(
    id: 'test_completed',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '已完成',
    trigger: '任务状态为 completed',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-completed.png',
  ),
  GalleryScreenSpec(
    id: 'test_blocked',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '受阻',
    trigger: '任务状态为 blocked',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-blocked.png',
  ),
  GalleryScreenSpec(
    id: 'test_failed',
    module: GalleryModule.tools,
    title: '测试任务',
    route: '/tools/testing',
    state: '失败',
    trigger: '任务状态为 failed 或 unknown',
    surface: GallerySurface.testRuns,
    screenshotPath: 'tools/test-failed.png',
  ),
  GalleryScreenSpec(
    id: 'case_disconnected',
    module: GalleryModule.tools,
    title: '测试内容',
    route: '/tools/testing/cases',
    state: '需要连接机器人',
    trigger: '从工具进入测试内容但未连接',
    surface: GallerySurface.testCases,
    screenshotPath: 'tools/cases-disconnected.png',
  ),
  GalleryScreenSpec(
    id: 'case_loading',
    module: GalleryModule.tools,
    title: '测试内容',
    route: '/tools/testing/cases',
    state: '加载中',
    trigger: '目录请求尚未完成',
    surface: GallerySurface.testCases,
    screenshotPath: 'tools/cases-loading.png',
  ),
  GalleryScreenSpec(
    id: 'case_error',
    module: GalleryModule.tools,
    title: '测试内容',
    route: '/tools/testing/cases',
    state: '加载失败',
    trigger: '目录请求失败',
    surface: GallerySurface.testCases,
    screenshotPath: 'tools/cases-error.png',
  ),
  GalleryScreenSpec(
    id: 'case_empty',
    module: GalleryModule.tools,
    title: '测试内容',
    route: '/tools/testing/cases',
    state: '空目录',
    trigger: '已连接但没有测试内容',
    surface: GallerySurface.testCases,
    screenshotPath: 'tools/cases-empty.png',
  ),
  GalleryScreenSpec(
    id: 'case_ready',
    module: GalleryModule.tools,
    title: '测试内容',
    route: '/tools/testing/cases',
    state: '可选择与编辑',
    trigger: '目录请求成功',
    surface: GallerySurface.testCases,
    screenshotPath: 'tools/cases-ready.png',
  ),
  GalleryScreenSpec(
    id: 'case_validation',
    module: GalleryModule.tools,
    title: '测试内容',
    route: '/tools/testing/cases',
    state: '内容校验提示',
    trigger: '机器人端返回测试内容校验提示',
    surface: GallerySurface.testCases,
    screenshotPath: 'tools/cases-validation.png',
  ),
  GalleryScreenSpec(
    id: 'logs_disconnected',
    module: GalleryModule.tools,
    title: '运行记录',
    route: '/tools/logs',
    state: '需要连接机器人',
    trigger: '从工具进入记录但未连接',
    surface: GallerySurface.logs,
    screenshotPath: 'tools/logs-disconnected.png',
  ),
  GalleryScreenSpec(
    id: 'logs_loading',
    module: GalleryModule.tools,
    title: '运行记录',
    route: '/tools/logs',
    state: '加载中',
    trigger: '记录请求尚未完成',
    surface: GallerySurface.logs,
    screenshotPath: 'tools/logs-loading.png',
  ),
  GalleryScreenSpec(
    id: 'logs_error',
    module: GalleryModule.tools,
    title: '运行记录',
    route: '/tools/logs',
    state: '加载失败',
    trigger: '记录请求失败',
    surface: GallerySurface.logs,
    screenshotPath: 'tools/logs-error.png',
  ),
  GalleryScreenSpec(
    id: 'logs_empty',
    module: GalleryModule.tools,
    title: '运行记录',
    route: '/tools/logs',
    state: '没有记录',
    trigger: '记录请求成功但为空',
    surface: GallerySurface.logs,
    screenshotPath: 'tools/logs-empty.png',
  ),
  GalleryScreenSpec(
    id: 'logs_all',
    module: GalleryModule.tools,
    title: '运行记录',
    route: '/tools/logs',
    state: '全部记录',
    trigger: '记录请求成功',
    surface: GallerySurface.logs,
    screenshotPath: 'tools/logs-all.png',
  ),
  GalleryScreenSpec(
    id: 'logs_errors',
    module: GalleryModule.tools,
    title: '运行记录',
    route: '/tools/logs',
    state: '异常筛选',
    trigger: '用户选择异常筛选',
    surface: GallerySurface.logs,
    screenshotPath: 'tools/logs-errors.png',
  ),
  GalleryScreenSpec(
    id: 'reports_disconnected',
    module: GalleryModule.tools,
    title: '报告',
    route: '/tools/reports',
    state: '需要连接机器人',
    trigger: '从工具进入报告但未连接',
    surface: GallerySurface.reports,
    screenshotPath: 'tools/reports-disconnected.png',
  ),
  GalleryScreenSpec(
    id: 'reports_loading',
    module: GalleryModule.tools,
    title: '报告',
    route: '/tools/reports',
    state: '加载中',
    trigger: '报告请求尚未完成',
    surface: GallerySurface.reports,
    screenshotPath: 'tools/reports-loading.png',
  ),
  GalleryScreenSpec(
    id: 'reports_error',
    module: GalleryModule.tools,
    title: '报告',
    route: '/tools/reports',
    state: '加载失败',
    trigger: '报告请求失败',
    surface: GallerySurface.reports,
    screenshotPath: 'tools/reports-error.png',
  ),
  GalleryScreenSpec(
    id: 'reports_empty',
    module: GalleryModule.tools,
    title: '报告',
    route: '/tools/reports',
    state: '没有报告',
    trigger: '报告请求成功但为空',
    surface: GallerySurface.reports,
    screenshotPath: 'tools/reports-empty.png',
  ),
  GalleryScreenSpec(
    id: 'reports_ready',
    module: GalleryModule.tools,
    title: '报告',
    route: '/tools/reports',
    state: '报告列表',
    trigger: '报告请求成功',
    surface: GallerySurface.reports,
    screenshotPath: 'tools/reports-ready.png',
  ),
  GalleryScreenSpec(
    id: 'dialog_start',
    module: GalleryModule.global,
    title: '确认对话框',
    route: '/__debug/ui-gallery',
    state: '开始测试确认',
    trigger: '用户准备执行测试',
    surface: GallerySurface.dialog,
    screenshotPath: 'states/dialog-start.png',
  ),
  GalleryScreenSpec(
    id: 'dialog_cancel',
    module: GalleryModule.global,
    title: '确认对话框',
    route: '/__debug/ui-gallery',
    state: '中止测试确认',
    trigger: '用户中止正在进行的测试',
    surface: GallerySurface.dialog,
    screenshotPath: 'states/dialog-cancel.png',
  ),
  GalleryScreenSpec(
    id: 'dialog_recovery',
    module: GalleryModule.global,
    title: '确认对话框',
    route: '/__debug/ui-gallery',
    state: '恢复测试确认',
    trigger: '用户恢复受阻的测试',
    surface: GallerySurface.dialog,
    screenshotPath: 'states/dialog-recovery.png',
  ),
  GalleryScreenSpec(
    id: 'bottom_sheet',
    module: GalleryModule.global,
    title: '底部操作区',
    route: '/__debug/ui-gallery',
    state: 'Material BottomSheet',
    trigger: '需要在不离开当前页的情况下呈现操作',
    surface: GallerySurface.bottomSheet,
    screenshotPath: 'states/bottom-sheet.png',
  ),
  GalleryScreenSpec(
    id: 'snackbar',
    module: GalleryModule.global,
    title: '即时反馈',
    route: '/__debug/ui-gallery',
    state: 'SnackBar',
    trigger: '非阻塞的短暂结果反馈',
    surface: GallerySurface.snackbar,
    screenshotPath: 'states/snackbar.png',
  ),
  GalleryScreenSpec(
    id: 'permission',
    module: GalleryModule.global,
    title: '权限提示',
    route: '/__debug/ui-gallery',
    state: '权限尚未授予',
    trigger: '未来能力请求系统权限前',
    surface: GallerySurface.permission,
    screenshotPath: 'states/permission.png',
  ),
  GalleryScreenSpec(
    id: 'offline',
    module: GalleryModule.global,
    title: '离线提示',
    route: '/__debug/ui-gallery',
    state: '网络不可用',
    trigger: '通用网络不可用状态',
    surface: GallerySurface.offline,
    screenshotPath: 'states/offline.png',
  ),
  GalleryScreenSpec(
    id: 'empty_state',
    module: GalleryModule.global,
    title: '空状态',
    route: '/__debug/ui-gallery',
    state: '无内容',
    trigger: '通用无数据占位',
    surface: GallerySurface.empty,
    screenshotPath: 'states/empty-state.png',
  ),
];

GalleryScreenSpec galleryScreenById(String id) =>
    galleryScreenManifest.firstWhere(
      (spec) => spec.id == id,
      orElse: () => galleryScreenManifest.first,
    );
